/* This file was generated by upb_generator from the input file:
 *
 *     src/testing/test_message.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#ifndef SRC_TESTING_TEST_MESSAGE_PROTO_UPB_H__UPB_MINITABLE_H_
#define SRC_TESTING_TEST_MESSAGE_PROTO_UPB_H__UPB_MINITABLE_H_

#include "upb/generated_code_support.h"

// Must be last.
#include "upb/port/def.inc"

#ifdef __cplusplus
extern "C" {
#endif

extern const upb_MiniTable testing__TestMessage_msg_init;

extern const upb_MiniTableFile src_testing_test_message_proto_upb_file_layout;

#ifdef __cplusplus
}  /* extern "C" */
#endif

#include "upb/port/undef.inc"

#endif  /* SRC_TESTING_TEST_MESSAGE_PROTO_UPB_H__UPB_MINITABLE_H_ */
