// Generated by protoc-gen-zig-pb. DO NOT EDIT.
//! MiniTables for test_message.proto

const proto = @import("proto");
const MiniTable = proto.MiniTable;
const MiniTableField = proto.MiniTableField;
const FieldType = proto.FieldType;
const Mode = proto.Mode;

// .testing.TestMessage

const test_message_fields = [_]MiniTableField{
    .{
        .number = 1,
        .offset = 72,
        .presence = 0,
        .submsg_index = 65535,
        .field_type = .TYPE_INT32,
        .mode = .scalar,
        .is_packed = false,
    },
    .{
        .number = 2,
        .offset = 48,
        .presence = 0,
        .submsg_index = 65535,
        .field_type = .TYPE_STRING,
        .mode = .scalar,
        .is_packed = false,
    },
    .{
        .number = 3,
        .offset = 64,
        .presence = 0,
        .submsg_index = 65535,
        .field_type = .TYPE_INT64,
        .mode = .scalar,
        .is_packed = false,
    },
    .{
        .number = 4,
        .offset = 8,
        .presence = -1,
        .submsg_index = 65535,
        .field_type = .TYPE_INT32,
        .mode = .scalar,
        .is_packed = false,
    },
    .{
        .number = 5,
        .offset = 8,
        .presence = -1,
        .submsg_index = 65535,
        .field_type = .TYPE_STRING,
        .mode = .scalar,
        .is_packed = false,
    },
    .{
        .number = 6,
        .offset = 24,
        .presence = 0,
        .submsg_index = 65535,
        .field_type = .TYPE_INT32,
        .mode = .repeated,
        .is_packed = false,
    },
};

const test_message_submessages = [_]*const MiniTable{};

pub const test_message_table: MiniTable = .{
    .fields = &test_message_fields,
    .submessages = &test_message_submessages,
    .size = 76,
    .hasbit_bytes = 0,
    .oneof_count = 1,
    .dense_below = 6,
};

